ALTER TYPE "NotificationEventType" ADD VALUE 'BUTLER_ANOMALY_DAILY';
ALTER TYPE "NotificationEventType" ADD VALUE 'BUTLER_WEEKLY_REVIEW_FROZEN';
ALTER TYPE "NotificationEventType" ADD VALUE 'BUTLER_WEEKLY_REVIEW_SUBMITTED';
