ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'MATERIAL_DUE_SOON';
ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'MATERIAL_OVERDUE';
ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'MATERIAL_REVIEW_OVERDUE';
